#!/bin/bash

# u-boot image can be found in apt package u-boot-qemu
# qemu_boot is a script to boot Armbian on QEMU

random_mac() {
    printf '52:54:00:%02X:%02X:%02X' $((RANDOM%256)) $((RANDOM%256)) $((RANDOM%256))
}

# get image file path
IMAGE_PATH=$1
MAC=$(random_mac)

qemu-system-aarch64 -machine virt -cpu cortex-a57 -nographic -smp 1 -m 256 \
    -drive file=qemu_flash/output/flash0.bin,format=raw,if=pflash \
    -drive file=qemu_flash/output/flash1.bin,format=raw,if=pflash \
    -drive if=none,file=${IMAGE_PATH},id=scsi0 -device ich9-ahci,id=ahci -device ide-hd,drive=scsi0,bus=ahci.0 \
    -netdev user,hostfwd=tcp::60022-:22,id=mynet0 -device e1000,netdev=mynet0,mac=52:55:00:d1:55:01
